# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/d3eb4363-323b-4763-9226-a4bd3a66e030";

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/btrfs" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/e2ca6468-6a92-4fd6-84ff-88873ba02d12";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2825-DDBA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
